AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless stack for the S3 Doc Viewer Lambdas

Parameters:
  BucketName:
    Type: String
    Default: avivdocdev
    Description: S3 bucket that stores documents

Resources:
  # ----------------------------- Functions -----------------------------
  GenerateS3PresignedUrl:
    Type: AWS::Serverless::Function
    Properties:
      # Use the pre-created execution role (do NOT create roles in this stack)
      Role: arn:aws:iam::992382709732:role/GenerateS3PresignedUrl
      CodeUri: lambda/GenerateS3PresignedUrl/src
      Description: Generates pre-signed S3 URLs for uploads and downloads
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures: [ x86_64 ]
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          BUCKET: !Ref BucketName
      Events:
        PresignPut:
          Type: Api
          Properties:
            Path: /generate-presigned-url
            Method: POST
        PresignGet:
          Type: Api
          Properties:
            Path: /generate-presigned-get-url
            Method: POST

  MsgToEml:
    Type: AWS::Serverless::Function
    Properties:
      # Use the pre-created execution role (do NOT create roles in this stack)
      Role: arn:aws:iam::992382709732:role/MsgToEml-role-8w9n0xf0
      CodeUri: lambda/MsgToEml/src
      Description: Converts .msg email files to HTML and attachments
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures: [ x86_64 ]
      MemorySize: 256
      Timeout: 60
      Environment:
        Variables:
          TARGET_BUCKET: !Ref BucketName
      Events:
        Convert:
          Type: Api
          Properties:
            Path: /convert
            Method: POST

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL for the default stage
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
