name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      # ── checkout code ──────────────────────────────────────────────
      - uses: actions/checkout@v4

      # ── Node toolchain for LWC lint / Jest tests ──────────────────
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm test

      # ── light sanity check of the Lambda code ──────────────────────
      - name: Check Python syntax
        run: python -m compileall lambda

      # ── install latest Salesforce CLI (sf ≥2.100) ─────────────────
      - run: npm install -g @salesforce/cli

      # ── authenticate to the scratch / CI org ──────────────────────
      - name: Authenticate to Salesforce
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth-url.txt
          sf org login sfdx-url --sfdx-url-file auth-url.txt --alias testOrg --json

      # ── validate metadata & run all Apex tests (no changes pushed) ─
      - name: Validate deploy & run tests
        run: |
          sf project deploy start \
            -d force-app \
            -o testOrg \
            --dry-run \
            --test-level RunLocalTests