name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      # ── checkout code ──────────────────────────────────────────────
      - uses: actions/checkout@v4

      # ── Node toolchain for LWC lint / Jest tests ──────────────────
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm test

      # ── light sanity check of the Lambda code ──────────────────────
      - name: Check Python syntax
        run: python -m compileall lambda

      # ── install latest Salesforce CLI (sf ≥2.100) ─────────────────
      - run: npm install -g @salesforce/cli

      # ── authenticate to the scratch / CI org ──────────────────────
      - name: Authenticate to Salesforce
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth-url.txt
          sf org login sfdx-url --sfdx-url-file auth-url.txt --alias testOrg --json

      # ── run Apex tests to capture code coverage ───────────────────
      - name: Run Apex tests with coverage
        run: sf apex run test --target-org testOrg --code-coverage --result-format json --output-dir coverage --synchronous

      # ── run LWC tests and build coverage markdown ─────────────────
      - run: npm run coverage:md

      - name: Commit updated coverage
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: docs/code-coverage.md
          message: 'chore: update coverage [skip ci]'