name: CI
on:
  push:
    branches: [main]        # validate every push to main
  pull_request:             # …and every PR

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      # ─── pull the repo ───────────────────────────────────────────────
      - name: Checkout repo
        uses: actions/checkout@v4

      # ─── Node toolchain (for your LWC/eslint/jest steps) ────────────
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm test

      # ─── quick syntax sweep of the Lambda sources ───────────────────
      - name: Check Python syntax
        run: python -m compileall lambda

      # ─── Salesforce CLI ─────────────────────────────────────────────
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to CI org
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}   # <-- store once in repo secrets
        run: |
          echo "$SFDX_AUTH_URL" > auth-url.txt
          sf org login sfdx-url --sfdx-url-file auth-url.txt --alias testOrg --json

      # ─── Validate & run all Apex tests (no changes pushed) ──────────
      - name: Validate deploy + run tests
        run: |
          sf project deploy start \
            --metadata-dir force-app \     # change only if your source lives elsewhere
            --target-org testOrg \
            --dry-run \                    # = old --check-only
            --test-level RunLocalTests \
            --json
