name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out the repo
      - uses: actions/checkout@v4

      # 2️⃣  Node – for LWC lint/tests
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm test

      # 3️⃣  Quick Python syntax sweep of ./lambda
      - name: Check Python syntax
        run: python -m compileall lambda

      # 4️⃣  Install the Salesforce CLI (latest)
      - run: npm install -g @salesforce/cli

      # 5️⃣  Authenticate to the scratch / packaging org
      - name: Auth to Salesforce
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth-url.txt
          sf org login sfdx-url \
            --sfdx-url-file auth-url.txt \
            --alias testOrg \
            --no-prompt \
            --set-default

      # 6️⃣  Validate metadata & run all Apex tests (CHECK-ONLY)
      - name: Validate deploy + run tests
        run: sf project deploy start --source-dir force-app -o testOrg --check-only --test-level RunLocalTests
