name: CD
on:
  push:
    branches: [main]        # auto-deploy everything merged to main
  workflow_dispatch:        # …or manual trigger

jobs:
  # ────────────────────────────────────────────────────────────────────
  deploy-salesforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to deployment org
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}   # same secret, but may point to prod/sandbox
        run: |
          echo "$SFDX_AUTH_URL" > auth-url.txt
          sf org login sfdx-url --sfdx-url-file auth-url.txt --alias deployOrg --json

      - name: Deploy to Salesforce
        run: sf project deploy start --target-org deployOrg

  # ────────────────────────────────────────────────────────────────────
  deploy-lambda:
    runs-on: ubuntu-latest
    needs: deploy-salesforce          # waits for the SF deploy to finish

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Build Lambda package(s)
        run: sam build

      - name: Deploy Lambda stack
        run: |
          sam deploy \
            --stack-name doc-viewer \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM
