name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-salesforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - run: npm ci

      - name: Authenticate to Salesforce
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth-url.txt
          sfdx auth:sfdxurl:store -f auth-url.txt -a deployOrg

      - name: Deploy to Salesforce
        run: sfdx force:source:deploy -p force-app -u deployOrg

  deploy-lambda:
    runs-on: ubuntu-latest
    needs: deploy-salesforce
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam build
      - run: sam deploy --stack-name doc-viewer --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
